### Site Settings ###
title: Pai Hwai
# logo: images/head_shot.png
description: data science porfolio
email: phwai2002@gmail.com
show_downloads: true
theme: jekyll-theme-minimal


### Navigation Menus ###
header_navigation:

  - title: LinkedIn
    url: www.linkedin.com/in/pai-hwai-3377681b7
    
  - title: E-mail
    url: mailto:phwai2002@gmail.com
    
