### Site Settings ###
title: Pai Hwai
logo: images/head_shot.png
description: 'Inquisitive. Tech enthusist. Creating data driven results for AI powered solutions.'
email: phwai2002@gmail.com
show_downloads: true
theme: jekyll-theme-midnight
background: black

### Navigation Menus ###
header_navigation:

  - title: LinkedIn
    url: www.linkedin.com/in/pai-hwai-3377681b7
    
  - title: email
    url: mailto:phwai2002@gmail.com
    
